//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PId { get; set; }
        public int CId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal VAT { get; set; }
        public decimal TotalPaidAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime ValidDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
